# fly.toml app configuration file generated for pocket-planner-api on 2023-11-02T07:53:40-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pocket-planner-api"
primary_region = "gru"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
[[http_service.checks]]
interval = "30s"
grace_period = "10s"
method = "GET"
path = "/api/health/"
protocol = "https"
timeout = "5s"
tls_skip_verify = true
