# fly.toml app configuration file generated for pocket-planner-api on 2023-11-02T07:53:40-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pocket-planner-api"
primary_region = "gru"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

[[services.http_checks]]
interval = 10000
grace_period = "5s"
method = "get"
path = "/health"
protocol = "https"
timeout = 2000
tls_skip_verify = false
[services.http_checks.headers]
